name: Deploy Webex Chatbot to Azure

on:
  push:
    branches:
      - main  # Deploy sa spustí pri pushnutí na "main" branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kódu
        uses: actions/checkout@v3

      - name: Nastavenie Python prostredia
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Inštalácia závislostí
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Nasadenie do Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "webex-chatbot"  # Názov Azure Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
